import md5 from "md5";
export const defaultState = {
  //   session: {
  //     authenticated: true,
  //   },
  clientContactDetails: [
    {
      id: "CA1",
      client: "C1",
      address1: "Blk 1, Lot 2, Mellow St.",
      address2: "",
      city: "Lapoe",
      state: "Ubec",
      zip: "6015",
      officePhoneNumber: "090-840-0432",
      officePhoneNumberExt: "875",
      cellPhoneNumber: "234-523-4523",
      alternativePhoneNumber: "234-523-4523",
      faxNumber: "234-523-4523",
      alternateEmail: "",
      workEmail: "",
    },
  ],
  clientContactDetailsSuggestions: [
    {
      id: "CDS1",
      client: "C1",
      address1: "Address 1",
      address2: "",
      workEmail: "",
      alternateEmail: "",
      city: "City 1",
      state: "State 1",
      zip: "Zip 1",
      officePhoneNumber: "567-856-7856",
      officePhoneNumberExt: "",
      cellPhoneNumber: "",
      alternativePhoneNumber: "",
      faxNumber: "",
      userid: "User2",
    },
  ],
  clients: [
    {
      id: "C1",
      name: "Peter Suarez",
      email: "peter.suarez@yahoo.com",
      website: "https://www.47digits.com",
      postNominalLetters: "MD",
      nameOfOrg: "47digits",
      titleWithOrg: "Owner",
      licenseNumber: "34634674567",
      licenseExpiryDate: "2025-01-01",
      licenseLastVerifiedDate: "2019-01-12",
      typeOfOrg: "Primary Care Physician",
      populationsServed: ["Children (ages 4-10)", "Pre-teens – (ages 10-12)"],
      typesOfServices: ["Couples", "Groups"],
      specialties: ["Specialty 3"],
      groupsOffered: ["Group 1"],
      insuranceAccepted: ["Aetna (In Network)", "Other (In Network)"],
      assignedLocations: ["North", "Clear Lake", "The Woodlands", "West"],
      notes: "admin notes UPDATED",
      users: ["Peep Madz"],
    },

    {
      id: "C2",
      name: "Kendall Smith",
      email: "kendall-smith@email.com",
      website: "https://www.website.com",
      postNominalLetters: "PhD",
      nameOfOrg: "WFH",
      titleWithOrg: "Manager",
      licenseNumber: "34634674567-00",
      licenseExpiryDate: "2020-12-12",
      licenseLastVerifiedDate: "2019-01-01",
      typeOfOrg: "Chiropractor",
      populationsServed: ["Children (ages 4-10)"],
      typesOfServices: ["Individual"],
      specialties: ["Specialty 1", "Specialty 2", "Specialty 3"],
      groupsOffered: ["Group 1"],
      insuranceAccepted: ["PHCS (In Network)", "United (In Network)"],
      assignedLocations: ["North", "West", "Katy", "East"],
      notes: "admin notes",
      users: ["Peep Madz", "Juan Dela Cruz", "Mikkel Jordan"],
    },

    {
      id: "C3",
      name: "David Copperfield",
      address: "890 Some St, Suite 201, Nice City, TX 7777",
      phone: "565-654-777-444",
      ext: "332",
      cell: "765-958-888-979",
      email: "me@mydomain.com",
      fax: "796-5464-999",
      owner: "User1",
    },
  ],
  locations: [
    // {
    //   id: "L1",
    //   location: "North",
    // },
    // {
    //   id: "L2",
    //   location: "East",
    // },
    {
      id: "L3",
      location: "Clear Lake",
    },
    {
      id: "L4",
      location: "Katy",
    },
    {
      id: "L5",
      location: "The Woodlands",
    },
    {
      id: "L6",
      location: "Others",
    },
    // {
    //   id: "L6",
    //   location: "South",
    // },
    // {
    //   id: "L7",
    //   location: "West",
    // },
  ],
  myfavorites: [
    {
      id: "F2",
      client: "C2",
      owner: "User2",
    },
  ],
  personalnotes: [
    {
      id: "e5f3f6ec-9387-4f21-8fd8-938e290baa79",
      client: "C1",
      note: "mikkel notes",
      datetimecreated: "9/25/2020, 12:14:11 AM",
      owner: "User2",
      isVerified: true,
    },
  ],
  users: [
    {
      id: "User1",
      firstName: "Peep",
      lastName: "Madz",
      location: ["North", "South", "West", "East"],
      officePhoneNumber: "123-569-6666",
      cellPhoneNumber: "456-678-9678",
      email: "admin@nddcrm.com",
      username: "Admin",
      isApproved: true,
      dateCreated: "1/1/2020, 12:00:00 AM",
      dateAprroved: null,
      passwordHash: md5("ADMIN"),
    },
    {
      id: "User2",
      firstName: "Juan",
      lastName: "Dela Cruz",
      location: ["North", "East"],
      officePhoneNumber: "123-756-9788",
      cellPhoneNumber: "456-789-7908",
      email: "jdc@nddcrm.com",
      username: "User",
      isApproved: true,
      passwordHash: "ee11cbb19052e40b07aac0ca060c23ee",
      dateCreated: "1/1/2020, 12:00:00 AM",
      dateAprroved: null,
    },
  ],
};
